### ISSUE TITLE
Source code not updated

### ISSUE THREAD

**Issue by jvyden** [TheBobPony/RaspberryPE#1]
The source is still on 0.1, not 0.2. Release the source code, please. Thank you.

**Comment by TheBobPony** [comment]
Will do later. ;)

**Comment by jvyden** [comment]
OK, as soon as this issue gets mentioned in a commit (just type #1 in a commit) ill close it

**Comment by jvyden** [comment]
Please do this soon, as i want to contribute and not have to worry about shit conflicting
